network:
  version: 2
  ethernets:
     ens160:
       dhcp4: no
       addresses:
        - 172.16.1.16/24
       gateway4: 172.16.1.2
       nameservers:
         search: [group1.local]
         addresses: [172.16.1.12, 172.16.1.13]
